### ISSUE TITLE
paragraph tags appearing in HDX SOURCE

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#8] opened 2015-06-12 09:31 UTC
![image](https://cloud.githubusercontent.com/assets/1654485/8127383/8819c00a-10f6-11e5-9ed7-eb022cbaef29.png)
e

**Comment by teodorescuserban** [comment] 2015-06-12 09:50
duplicate of #7

**Closed as completed by teodorescuserban** 2015-06-12 09:50 UTC
